- name: Configure Nginx with Self-Signed SSL
  become: true
  vars:
    domain: "34.207.215.186"
    ssl_cert_path: "/etc/ssl/certs/{{ domain }}.crt"
    ssl_key_path: "/etc/ssl/prt/{{ domain }}.key"

  block:

  - name: Copy SSL certificate to Nginx server
    copy:
      src: "../{{ domain }}.crt"
      dest: "{{ ssl_cert_path }}"

  - name: Copy SSL certificate key to Nginx server
    copy:
      src: "../{{ domain }}.key"
      dest: "{{ ssl_key_path }}"

  - name: Configure Nginx to use SSL
    blockinfile:
      path: /etc/nginx/sites-available/default
      block: |
        server {
          listen 443 ssl;
          server_name {{ domain }};

          ssl_certificate {{ ssl_cert_path }};
          ssl_certificate_key {{ ssl_key_path }};

          location / {
            root /var/www/html;
            index index.html index.htm;
          }
        }

        server {
          listen 80;
          server_name {{ domain }};
          return 301 https://$server_name$request_uri;
        }

